=== sayushkhadka/GiftCardStore/[XML] GIft Card Store/catalog_20049034.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Schema declaration-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
attributeFormDefault="unqualified" 
elementFormDefault="qualified">

<!-- main element with child elements-->
  <xs:element name="stores">
    <xs:complexType>

      <!-- use of sequence-->
      <xs:sequence>

        <xs:element name="heading">
        <xs:complexType>
        <xs:sequence>

            <!-- empty element logo-->
            <xs:element name="logo" />
            <xs:element name="navBar">
                <xs:complexType>
                  <xs:sequence>
                  
                  <!-- nav element occurs once and more than once-->
                <xs:element  name="nav" maxOccurs="unbounded" type="xs:string" />
                </xs:sequence>
                </xs:complexType>
                </xs:element>

              <xs:element name="navBar2">
                <xs:complexType>
                  <xs:sequence>

                  <!-- empty elements-->
                    <xs:element name="userImage" />
                    <xs:element name="cart" />
                    <xs:element name="bonus" />
                  </xs:sequence>
                </xs:complexType>
                    </xs:element>
                </xs:sequence>
                </xs:complexType>
                 </xs:element>

              <!-- store details-->
              <xs:element name="storeDetails">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="storeName" type="xs:string" />
                  <xs:element name="storeInfo" type="xs:string" />
                </xs:sequence>
              </xs:complexType>
              </xs:element>

              <!-- store-->
                  <xs:element name="store">
                    <xs:complexType>
                      <xs:sequence>

                      <!-- products-->
                          <xs:element name="products">
                            <xs:complexType>
                                <xs:sequence>

                                <!-- product occurs one or more than once-->
                            <xs:element name="product" maxOccurs="unbounded" >
                                <xs:complexType>
                                    <xs:sequence>

                                      <!-- empty element product image-->
                                        <xs:element name="productImage" />
                                        <xs:element name="card">
                                          <xs:complexType>
                                                  <xs:sequence>
                                                        <!-- restriction on product number to be "positiveInterger"-->
                                                            <xs:element name="productNo" > 
                                                              <xs:simpleType>
                                                                <xs:restriction base="xs:positiveInteger">
                                                                </xs:restriction>
                                                              </xs:simpleType>
                                                            </xs:element>
                                                            <xs:element name="name" type="xs:string" />
                                                            
                                                            <!-- restriction given to type of cards-->
                                                            <xs:element  name="type">
                                                              <xs:simpleType>
                                                                <xs:restriction base="xs:string">

                                                                <!-- pattern =  "Type : Physical Card|Type : Digital Card"-->
                                                                    <xs:pattern value="Type : Physical Card|Type : Digital Card"/>
                                                                </xs:restriction>
                                                              </xs:simpleType>
                                                            </xs:element>

                                                            <xs:element name="cost" type="xs:string" />

                                                            <!-- restriction and enumeration for valid time period of the card-->
                                                            <xs:element name="valid">
                                                              <xs:simpleType> 
                                                                <xs:restriction base="xs:string">
                                                                  <xs:enumeration value="Valid : 1 Month"/>
                                                                  <xs:enumeration value="Valid : 2 Months"/>
                                                                  <xs:enumeration value="Valid : 3 Months"/>
                                                                  <xs:enumeration value="Valid : 4 Months"/>
                                                                  <xs:enumeration value="Valid : 5 Months"/>
                                                                  <xs:enumeration value="Valid : 6 months"/>
                                                                  <xs:enumeration value="Valid : 7 Months"/>
                                                                  <xs:enumeration value="Valid : 8 Months"/>
                                                                  <xs:enumeration value="Valid : 9 Months"/>
                                                                  <xs:enumeration value="Valid : 10 Months"/>
                                                                  <xs:enumeration value="Valid : 11 Months"/>
                                                                  <xs:enumeration value="Valid : 12 Months"/>
                                                                  <xs:enumeration value="Valid : 1 year"/>
                                                                  <xs:enumeration value="Valid : 2 years"/>
                                                                  <xs:enumeration value="Valid : always"/>
                                                                </xs:restriction>

                                                                </xs:simpleType> 

                                                            </xs:element>

                                                            <xs:element  name="numberOfUsers" type="xs:string" />
                                                            <xs:element name="discount" type="xs:string" />

                                                            <!-- optional datas with minOccurs=0-->
                                                            <xs:element  name="validGames" type="xs:string" minOccurs="0"/>
                                                            <xs:element name="offer" type="xs:string" minOccurs="0" />
                                                            <xs:element  name="validLocation" type="xs:string" minOccurs="0" />
                                                            <xs:element  name="avialability" type="xs:string" minOccurs="0"/>
                                                            <xs:element name="shippingCost" type="xs:string" minOccurs="0"/>

                                                  </xs:sequence>
                                                    </xs:complexType>
                                                    </xs:element>
                                                  </xs:sequence>

                                                            <!-- required attribute with type string-->
                                                            <xs:attribute name="productID" type="xs:string" use="required" />
                                                            </xs:complexType>
                                                          </xs:element>
                                                        </xs:sequence>
                                                        </xs:complexType>
                                                        </xs:element>
                                                      </xs:sequence>

                                                      <!-- required attribute with type string-->
                                                    <xs:attribute name="storeType" type="xs:string" use="required" />
                                                  </xs:complexType>
                                                  </xs:element>

                                                  <!-- contactDetails-->
                                                  <xs:element name="contactDetails">
                                                    <xs:complexType>
                                                      <xs:sequence>

                                                  <xs:element name="left">
                                                    <xs:complexType>
                                                      <xs:sequence>

                                                      <xs:element name="location">
                                                        <!-- mixed complexType element-->
                                                        <xs:complexType mixed="true">
                                                            <xs:sequence>

                                                              <xs:element name="details">
                                                                 <xs:complexType>
                                                                   <!-- optional attribute with default value as "Location: London"-->
                                                                    <xs:attribute name="location" type="xs:string" default="Location: London" use="optional" />
                                                                      </xs:complexType>
                                                                        </xs:element>
                                                                       </xs:sequence>
                                                                      </xs:complexType>
                                                                    </xs:element>

                                                                  <xs:element name="website">
                                                                    <!-- mixed complexType element-->
                                                                  <xs:complexType mixed="true">
                                                                  <xs:sequence>
                                                                    <xs:element name="details">
                                                                    <xs:complexType>

                                                                      <!-- required attribute with type string-->
                                                                        <xs:attribute name="website" type="xs:string" use="required" />
                                                                      </xs:complexType>
                                                                    </xs:element>
                                                                        
                                                                  
                                                              </xs:sequence>
                                                                </xs:complexType>
                                                                    </xs:element>

                                                                <xs:element name="phone">
                                                                        <!-- mixed complexType element-->
                                                                        <xs:complexType mixed="true">
                                                                        <xs:sequence>
                                                                          <xs:element name="details">
                                                                            <xs:complexType>

                                                                           <!-- optional attribute with deafault value as "Telephone: +449801329901"-->
                                                                          <xs:attribute name="phone" type="xs:string" default="Telephone: +449801329901" use="optional" />
                                                                         </xs:complexType>
                                                                      </xs:element>
                                                                  </xs:sequence>
                                                                </xs:complexType>
                                                            </xs:element>
                                                      </xs:sequence>
                                                        </xs:complexType>
                                                              </xs:element>


                                                              <xs:element name="right">
                                                          <xs:complexType>
                                                       <xs:sequence>

                                                 <!-- contacts-->
                                                  <xs:element name="contacts">
                                                    <xs:complexType>
                                                        <xs:sequence>

                                                                              
                                                        <xs:element name="connect" type="xs:string" />
                                                         <!-- contact occurs once or more than once-->
                                                          <xs:element  name="contact" minOccurs="1" maxOccurs="unbounded">
                                                          <xs:complexType>
                                                          <!-- required atrribute with string type-->
                                                          <xs:attribute name="type" type="xs:string" use="required" />
                                                  </xs:complexType>
                                          </xs:element>
                                            </xs:sequence>
                                          </xs:complexType>
                                    </xs:element>
                                      </xs:sequence>
                                      </xs:complexType>
                                    </xs:element>
                                  </xs:sequence>
                            </xs:complexType>
                              </xs:element>
                            </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                      </xs:schema>

=== sayushkhadka/GiftCardStore/[XML] GIft Card Store/catalog_20049034.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- css link-->
<?xml-stylesheet href="./catalog_20049034.css" type="text/css"?>

<!-- Schema link-->
<stores xsi:noNamespaceSchemaLocation="catalog_20049034.xsd"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <!-- heading -->
    <heading>
    <!-- logo of the store-->
        <logo/>
        <!-- navigation bar-->
        <navBar>
            <!-- navigation contents-->
            <nav>Home nez</nav>
            <nav>Buy with nez</nav>
            <nav>Connect with nez</nav>
        </navBar>

        <!-- second navigation bar for userImage,cart and bonus icon-->
        <navBar2>
                <userImage/>
                <cart/>
                <bonus/>
        </navBar2>

    </heading>

    <!-- details of the store-->
    <storeDetails>
        
            <storeName>nez</storeName>
            <storeInfo>
                Purchase gift cards for the perfect gift for yourself and for the people you care.
            </storeInfo>
        
    </storeDetails>

    <!-- store with attribute "giftcards"-->
    <store storeType="giftcards">

        <!-- products of the store-->
        <products>

            <!-- list of products in the store with their attribute-->
            <product productID="product1">
                <!-- product image-->
                <productImage/>
                <!-- product description-->
                <card>
                    <productNo>1</productNo>
                    <name>Name : Netflix Gift Card</name>
                    <type>Type : Physical Card</type>
                    <cost>Price : $ 30</cost>
                    <valid>Valid : 1 Month</valid>
                    <numberOfUsers>Number of Users: 50</numberOfUsers>
                    <discount>Discount : $ 5</discount>
                </card>
            </product>

            <product productID="product2">
                <productImage/>
                <card>
                    <productNo>2</productNo>
                    <name>Name : Google Gift Card</name>
                    <type>Type : Physical Card</type>
                    <cost>Price : $ 100</cost>
                    <valid>Valid : 3 Months</valid>
                    <numberOfUsers>Number of Users: 30</numberOfUsers>
                    <discount>Discount : $ 10</discount>
                    <shippingCost>Shipping Cost: $10</shippingCost>
                </card>
            </product>

            <product productID="product3">
                <productImage/>
                <card>
                    <productNo>3</productNo>
                    <name>Name : Amazon Gift Card</name>
                    <type>Type : Digital Card</type>
                    <cost>Price : $ 500</cost>
                    <valid>Valid : 2 years</valid>
                    <numberOfUsers>Number of Users: 10</numberOfUsers>
                    <discount>Discount : $50</discount>
                    <avialability>Avialability : 3 left only</avialability>
                </card>
            </product>

            <product productID="product4">
                <productImage/>
                <card>
                    <productNo>4</productNo>
                    <name>Name : Spotify Gift Card</name>
                    <type>Type : Digital Card</type>
                    <cost>Price : $ 99</cost>
                    <valid>Valid : 12 Months</valid>
                    <numberOfUsers>Number of Users: 40</numberOfUsers>
                    <discount>Discount : $ 20</discount>
                </card>
            </product>

            <product productID="product5">
                <productImage/>
                <card>
                    <productNo>5</productNo>
                    <name>Name : Apple Gift Card</name>
                    <type>Type : Physical Card</type>
                    <cost>Price : $ 50</cost>
                    <valid>Valid : 2 Months</valid>
                    <numberOfUsers>Number of Users: 20</numberOfUsers>
                    <discount>Discount : n/a</discount>
                    <avialability>Avialability : 2 left only</avialability>
                </card>
            </product>

            <product productID="product6">
                <productImage/>
                <card>
                    <productNo>6</productNo>
                    <name>Name : Xbox Gift Card</name>
                    <type>Type : Digital Card</type>
                    <cost>Price : $ 25</cost>
                    <valid>Valid : 1 Month</valid>
                    <numberOfUsers>Number of Users: 13</numberOfUsers>
                    <discount>Discount : n/a</discount>
                </card>
            </product>

            <product productID="product7">
                <productImage/>
                <card>
                    <productNo>7</productNo>
                    <name>Name : Play Station Card</name>
                    <type>Type : Digital Card</type>
                    <cost>Price : $ 50</cost>
                    <valid>Valid : 3 Months</valid>
                    <numberOfUsers>Number of Users: 19</numberOfUsers>
                    <discount>Discount : n/a</discount>
                </card>
            </product>

            <product productID="product8">
                <productImage/>
                <card>
                    <productNo>8</productNo>
                    <name>Name : PUBG UC Card</name>
                    <type>Type : Digital Card</type>
                    <cost>Price : $ 15</cost>
                    <valid>Valid : always</valid>
                    <numberOfUsers>Number of Users: 55</numberOfUsers>
                    <discount>Discount : n/a</discount>
                    <validLocation>Valid Location : Nepal and India only.</validLocation>
                </card>
            </product>

            <product productID="product9">
                <productImage/>
                <card>
                    <productNo>9</productNo>
                    <name>Name : Hulu Gift Card</name>
                    <type>Type : Digital Card</type>
                    <cost>Price : $ 100</cost>
                    <valid>Valid : 4 Months</valid>
                    <numberOfUsers>Number of Users: 4</numberOfUsers>
                    <discount>Discount : $ 10</discount>
                </card>
            </product>

            <product productID="product10">
                <productImage/>
                <card>
                    <productNo>10</productNo>
                    <name>Name : Razer Gift Card</name>
                    <type>Type : Physical Card</type>
                    <cost>Price : $ 200</cost>
                    <valid>Valid : 6 months</valid>
                    <numberOfUsers>Number of Users: 5</numberOfUsers>
                    <discount>Discount : n/a</discount>
                    <shippingCost>Shipping Cost: $10</shippingCost>
                </card>
            </product>

            <product productID="product11">
                <productImage/>
                <card>
                    <productNo>11</productNo>
                    <name>Name : Discord Nitro Card</name>
                    <type>Type : Digital Card</type>
                    <cost>Price : $ 10</cost>
                    <valid>Valid : 1 Month</valid>
                    <numberOfUsers>Number of Users: 22</numberOfUsers>
                    <discount>Discount : n/a</discount>
                </card>
            </product>

            <product productID="product12">
                <productImage/>
                <card>
                    <productNo>12</productNo>
                    <name>Name : Apple Msuic Card</name>
                    <type>Type : Digital Card</type>
                    <cost>Price : $ 90</cost>
                    <valid>Valid : 12 Months</valid>
                    <numberOfUsers>Number of Users: 19</numberOfUsers>
                    <discount>Discount : $ 10</discount>
                    <offer>Offer: Any 1 extra album free.</offer>
                </card>
            </product>

            <product productID="product13">
                <productImage/>
                <card>
                    <productNo>13</productNo>
                    <name>Name : Steam Gift Card</name>
                    <type>Type : Digital Card</type>
                    <cost>Price : $ 100</cost>
                    <valid>Valid : 12 Months</valid>
                    <numberOfUsers>Number of Users: 33</numberOfUsers>
                    <discount>Discount : $ 10</discount>
                    <validGames>Valid Games: Games above $40.</validGames>
                </card>
            </product>

            <product productID="product14">
                <productImage/>
                <card>
                    <productNo>14</productNo>
                    <name>Name : Twitch Gift Card</name>
                    <type>Type : Physical Card</type>
                    <cost>Price : $ 25</cost>
                    <valid>Valid : 2 Months</valid>
                    <numberOfUsers>Number of Users: 7</numberOfUsers>
                    <discount>Discount : n/a</discount>
                </card>
            </product>

            <product productID="product15">
                <productImage/>
                <card>
                    <productNo>15</productNo>
                    <name>Name : CSGO.net Gift Card</name>
                    <type>Type : Physical Card</type>
                    <cost>Price : $ 20</cost>
                    <valid>Valid : 2 Months</valid>
                    <numberOfUsers>Number of Users: 35</numberOfUsers>
                    <discount>Discount : n/a</discount>
                </card>
            </product>

        </products>
    </store>

    <!-- contact deatils of the store-->
    <contactDetails>
        <left>

            <!-- location of the store -->
            <location>
                <details location="location" />Location: London
